development:
  adapter: postgresql
  encoding: unicode
  database: eznounce_dev
  pool: 5
  username: jonathan
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: eznounce_test
  pool: 5
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: eznounce_prod
  pool: 5
  username: jonathan
  password:
